import os
import time
import asyncio
import json
import logging
from typing import AsyncGenerator, Dict, Any, List

logger = logging.getLogger("studio_service")

# In-memory session store: session_id -> js_source
session_modules: Dict[str, str] = {}

SPECS_DIR = "content/ruby-tv"
SPEC_FILES = ["prd.md", "spec.md", "GEMINI.md", "design.md", "runbook.md"]

def get_specs_data() -> List[Dict[str, Any]]:
    """Reads the specification stack files and estimates token count."""
    specs = []
    for filename in SPEC_FILES:
        filepath = os.path.join(SPECS_DIR, filename)
        content = ""
        if os.path.exists(filepath):
            with open(filepath, "r", encoding="utf-8") as f:
                content = f.read()
        else:
            content = f"# {filename}\nSpecification file placeholder for Ruby TV."
        
        # Rough token estimate (~4 chars per token)
        tokens = max(1, len(content) // 4)
        specs.append({
            "name": filename,
            "path": filepath,
            "tokens": tokens,
            "content": content
        })
    return specs

def get_total_tokens(specs: List[Dict[str, Any]]) -> int:
    return sum(s["tokens"] for s in specs)

def generate_mock_js(tweak: str = None) -> str:
    """Generates realistic ES module JavaScript code based on the spec tweak."""
    tweak_lower = (tweak or "").lower()
    
    if "german" in tweak_lower or "de" in tweak_lower or "original" in tweak_lower:
        return """// Generated by Gemini 3.1 Pro (Spec Tweak: Prefer German-language originals for cold-start users)
export async function rank(userContext, watchHistory, deviceContext) {
  const isColdStart = !watchHistory || watchHistory.length === 0;

  if (isColdStart) {
    // Editorial fallback with aggressive boost for German Originals
    const catalog = [
      { id: 'orig1', title: 'Babylon Berlin', category: 'Crime', rating: 4.8, lang: 'DE', isOriginal: true, reason: 'Spec Rule: German-language Original prioritized for new users' },
      { id: 'orig2', title: 'Der Schwarm', category: 'Sci-Fi', rating: 4.5, lang: 'DE', isOriginal: true, reason: 'Spec Rule: German-language Original prioritized for new users' },
      { id: 'spo1', title: 'Bundesliga Live: FCB vs BVB', category: 'Sports', rating: 4.9, lang: 'DE', isOriginal: false, reason: 'Live Sports in DE: Top viewership event right now' },
      { id: 'doc2', title: 'Planet Earth III', category: 'Documentary', rating: 4.9, lang: 'EN', isOriginal: false, reason: 'Critically Acclaimed: Global documentary hit' }
    ];
    return catalog.sort((a, b) => (b.isOriginal ? 1 : 0) - (a.isOriginal ? 1 : 0));
  }

  // Existing user: Rank by watch progress & preferred language
  const recommendations = [
    { id: 'thr1', title: 'Dark', category: 'Sci-Fi / Thriller', rating: 4.9, lang: 'DE', isOriginal: true, reason: 'Top German Original match for your Sci-Fi preferences' },
    { id: 'orig1', title: 'Babylon Berlin', category: 'Crime', rating: 4.8, lang: 'DE', isOriginal: true, reason: 'German Original match based on your watch profile' },
    { id: 'sci2', title: '3 Body Problem', category: 'Sci-Fi', rating: 4.7, lang: 'EN', reason: 'Because you watched 65% of Dark Matter' },
    { id: 'doc3', title: 'Wild Germany', category: 'Documentary', rating: 4.6, lang: 'DE', reason: 'Because you enjoy German Documentaries' }
  ];

  return recommendations;
}
"""
    elif "sport" in tweak_lower or "live" in tweak_lower:
        return """// Generated by Gemini 3.1 Pro (Spec Tweak: Prioritize live sports over documentaries)
export async function rank(userContext, watchHistory, deviceContext) {
  const isColdStart = !watchHistory || watchHistory.length === 0;

  if (isColdStart) {
    // Cold-start fallback: Live Sports boosted to position #1
    return [
      { id: 'spo1', title: 'Bundesliga Live: FCB vs BVB', category: 'Sports', rating: 4.9, lang: 'DE', isOriginal: false, reason: 'Spec Rule: Live Sports prioritized over all documentaries' },
      { id: 'spo2', title: 'UEFA Champions League Highlights', category: 'Sports', rating: 4.8, lang: 'DE', isOriginal: false, reason: 'Spec Rule: Sports category boost active' },
      { id: 'orig1', title: 'Babylon Berlin', category: 'Crime', rating: 4.8, lang: 'DE', isOriginal: true, reason: 'Top German Original Drama' },
      { id: 'orig2', title: 'Der Schwarm', category: 'Sci-Fi', rating: 4.5, lang: 'DE', isOriginal: true, reason: 'Popular Sci-Fi Original in DE' }
    ];
  }

  // Existing user: Sports boosted above standard recommendations
  return [
    { id: 'spo1', title: 'Bundesliga Live: FCB vs BVB', category: 'Sports', rating: 4.9, lang: 'DE', reason: 'Spec Tweak: Sports prioritized for active viewers' },
    { id: 'sci2', title: '3 Body Problem', category: 'Sci-Fi', rating: 4.7, lang: 'EN', reason: 'Because you watched 65% of Dark Matter' },
    { id: 'orig1', title: 'Babylon Berlin', category: 'Crime', rating: 4.8, lang: 'DE', isOriginal: true, reason: 'Ruby TV Original recommendation' },
    { id: 'thr1', title: 'Dark', category: 'Sci-Fi / Thriller', rating: 4.9, lang: 'DE', reason: 'Top match for your thriller preference' }
  ];
}
"""
    elif "rating" in tweak_lower or "4." in tweak_lower or "filter" in tweak_lower:
        return """// Generated by Gemini 3.1 Pro (Spec Tweak: Filter out content with rating < 4.7)
export async function rank(userContext, watchHistory, deviceContext) {
  const isColdStart = !watchHistory || watchHistory.length === 0;

  const rawCatalog = isColdStart ? [
    { id: 'orig1', title: 'Babylon Berlin', category: 'Crime', rating: 4.8, lang: 'DE', isOriginal: true, reason: 'High Rating (4.8): Passes strict >= 4.7 filter' },
    { id: 'spo1', title: 'Bundesliga Live: FCB vs BVB', category: 'Sports', rating: 4.9, lang: 'DE', isOriginal: false, reason: 'High Rating (4.9): Passes strict >= 4.7 filter' },
    { id: 'doc2', title: 'Planet Earth III', category: 'Documentary', rating: 4.9, lang: 'EN', isOriginal: false, reason: 'High Rating (4.9): Passes strict >= 4.7 filter' },
    { id: 'thr1', title: 'Dark', category: 'Sci-Fi', rating: 4.9, lang: 'DE', isOriginal: true, reason: 'High Rating (4.9): Passes strict >= 4.7 filter' }
  ] : [
    { id: 'thr1', title: 'Dark', category: 'Sci-Fi / Thriller', rating: 4.9, lang: 'DE', reason: 'Rating 4.9 • Matches your Sci-Fi history' },
    { id: 'orig1', title: 'Babylon Berlin', category: 'Crime', rating: 4.8, lang: 'DE', isOriginal: true, reason: 'Rating 4.8 • Top Ruby TV Original' },
    { id: 'spo1', title: 'Bundesliga Live: FCB vs BVB', category: 'Sports', rating: 4.9, lang: 'DE', reason: 'Rating 4.9 • Trending Live Event' },
    { id: 'sci2', title: '3 Body Problem', category: 'Sci-Fi', rating: 4.7, lang: 'EN', reason: 'Rating 4.7 • Because you watched Dark Matter' }
  ];

  // Enforce rating threshold >= 4.7
  return rawCatalog.filter(item => (item.rating || 0) >= 4.7);
}
"""
    else:
        # Default high-performance ES module
        return """// Generated by Gemini 3.1 Pro (Standard Spec Assembly)
export async function rank(userContext, watchHistory, deviceContext) {
  const isColdStart = !watchHistory || watchHistory.length === 0;

  if (isColdStart) {
    // Standard editorial fallback rail
    return [
      { id: 'orig1', title: 'Babylon Berlin', category: 'Crime', rating: 4.8, lang: 'DE', isOriginal: true, reason: 'Editorial Highlight: Top-rated German original series' },
      { id: 'orig2', title: 'Der Schwarm', category: 'Sci-Fi', rating: 4.5, lang: 'DE', isOriginal: true, reason: 'Trending in DE: Popular Sci-Fi original' },
      { id: 'spo1', title: 'Bundesliga Live: FCB vs BVB', category: 'Sports', rating: 4.9, lang: 'DE', isOriginal: false, reason: 'Live Sports: High viewership event right now' },
      { id: 'doc2', title: 'Planet Earth III', category: 'Documentary', rating: 4.9, lang: 'EN', isOriginal: false, reason: 'Critically Acclaimed: Award-winning documentary' }
    ];
  }

  // Active user: Score by category affinity and watch history progress
  return [
    { id: 'sci2', title: '3 Body Problem', category: 'Sci-Fi', rating: 4.7, lang: 'EN', reason: 'Because you watched 65% of Dark Matter (Sci-Fi match)' },
    { id: 'doc3', title: 'Wild Germany', category: 'Documentary', rating: 4.6, lang: 'DE', reason: 'Because you enjoy Documentaries and German content' },
    { id: 'orig1', title: 'Babylon Berlin', category: 'Crime', rating: 4.8, lang: 'DE', isOriginal: true, reason: 'Ruby TV Original: Recommended for high engagement' },
    { id: 'thr1', title: 'Dark', category: 'Sci-Fi / Thriller', rating: 4.9, lang: 'DE', reason: 'Top match: Combines your Sci-Fi interest with German originals' }
  ];
}
"""

async def stream_recommender_generation(session_id: str, tweak: str = None) -> AsyncGenerator[str, None]:
    """Streams SSE events simulating Gemini 3.1 Pro generating the ES module."""
    specs = get_specs_data()
    total_tokens = get_total_tokens(specs)
    
    # Event 1: Assembling context
    status_msg = f"Assembling {total_tokens:,} tokens across {len(specs)} files → sending to Gemini 3.1 Pro"
    if tweak:
        status_msg += f" [Tweak: {tweak}]"
        
    yield f"data: {json.dumps({'type': 'status', 'message': status_msg, 'tokens': total_tokens})}\n\n"
    await asyncio.sleep(1.2)

    # Event 2: Streaming begins
    yield f"data: {json.dumps({'type': 'status', 'message': 'Streaming from gemini-3-1-pro ▮'})}\n\n"
    await asyncio.sleep(0.5)

    # Get target JS code
    full_js = generate_mock_js(tweak)

    # Stream character/line chunks
    lines = full_js.split("\n")
    for line in lines:
        chunk = line + "\n"
        yield f"data: {json.dumps({'type': 'chunk', 'text': chunk})}\n\n"
        await asyncio.sleep(0.08)

    # Store in session store
    session_modules[session_id] = full_js
    logger.info(f"Successfully generated and stored recommender module for session: {session_id}")

    # Event 3: Complete
    yield f"data: {json.dumps({'type': 'complete', 'path': '/demo/ruby/recommender.js', 'session_id': session_id, 'message': '✓ Written to /demo/ruby/recommender.js'})}\n\n"
